debug:
  SAVE_LOCAL_LATEST_IMG: true
  SAVE_S3: true
  SAVE_SQLITE: true
  SHOW_CAMERA_SETTINGS: true
  SHOW_TIMESTAMP: true
  SHOW_TIMING: false
fun_stuff:
  time_dilation:
    mode: sine
settings:
  DAY_BRIGHTNESS: 120
  ENABLED: true
  FREQUENCY: 74
  IMAGE_RETENTION_HOURS: 168
  MAX_RUNTIME_HOURS: 168
  NIGHT_BRIGHTNESS: 128
  SUNRISE_TIME: 05:45
  SUNSET_TIME: '20:15'
