debug:
  SAVE_LOCAL_LATEST_IMG: true
  SAVE_S3: true
  SHOW_CAMERA_SETTINGS: false
  SHOW_TIMESTAMP: true
  SHOW_TIMING: false
settings:
  DAY_BRIGHTNESS: 128
  FREQUENCY: 30
  IMAGE_RETENTION_HOURS: 168
  MAX_RUNTIME_HOURS: 168
  NIGHT_BRIGHTNESS: 120
  SUNRISE_TIME: 05:45
  SUNSET_TIME: '20:15'
  ENABLED: true
